version: '3'
services: 
  xrayr: 
    image: amfiyong/xray:latest
    volumes:
      - ./config.yml:/etc/XrayR/config.yml # 映射配置文件夹
      - ./dns.json:/etc/XrayR/dns.json 
      - ./rulelist:/etc/XrayR/rulelist
    restart: always
    network_mode: host
